config/routes.rb
AnimalRescueHub::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

	resources :animals, :only => [:index, :show]
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'application#index'

  match "/privacy_policy"  => 'pages#privacy_policy'
  match "/signup"          => 'users#new'
  get "signin",           to: "sessions#new"
  #the use of via: :delete for the signout route, which indicates that it should be invoked using an HTTP DELETE request
  match '/signout'         => 'sessions#destroy'

end

#== Route Map
# Generated on 14 May 2013 14:35
#
# batch_action_admin_admin_users POST       /admin/admin_users/batch_action(.:format) admin/admin_users#batch_action
#              admin_admin_users GET        /admin/admin_users(.:format)              admin/admin_users#index
#                                POST       /admin/admin_users(.:format)              admin/admin_users#create
#           new_admin_admin_user GET        /admin/admin_users/new(.:format)          admin/admin_users#new
#          edit_admin_admin_user GET        /admin/admin_users/:id/edit(.:format)     admin/admin_users#edit
#               admin_admin_user GET        /admin/admin_users/:id(.:format)          admin/admin_users#show
#                                PUT        /admin/admin_users/:id(.:format)          admin/admin_users#update
#                                DELETE     /admin/admin_users/:id(.:format)          admin/admin_users#destroy
#     batch_action_admin_animals POST       /admin/animals/batch_action(.:format)     admin/animals#batch_action
#                  admin_animals GET        /admin/animals(.:format)                  admin/animals#index
#                                POST       /admin/animals(.:format)                  admin/animals#create
#               new_admin_animal GET        /admin/animals/new(.:format)              admin/animals#new
#              edit_admin_animal GET        /admin/animals/:id/edit(.:format)         admin/animals#edit
#                   admin_animal GET        /admin/animals/:id(.:format)              admin/animals#show
#                                PUT        /admin/animals/:id(.:format)              admin/animals#update
#                                DELETE     /admin/animals/:id(.:format)              admin/animals#destroy
#                admin_dashboard            /admin/dashboard(.:format)                admin/dashboard#index
#    batch_action_admin_comments POST       /admin/comments/batch_action(.:format)    admin/comments#batch_action
#                 admin_comments GET        /admin/comments(.:format)                 admin/comments#index
#                                POST       /admin/comments(.:format)                 admin/comments#create
#                  admin_comment GET        /admin/comments/:id(.:format)             admin/comments#show
#         new_admin_user_session GET        /admin/login(.:format)                    active_admin/devise/sessions#new
#             admin_user_session POST       /admin/login(.:format)                    active_admin/devise/sessions#create
#     destroy_admin_user_session DELETE|GET /admin/logout(.:format)                   active_admin/devise/sessions#destroy
#            admin_user_password POST       /admin/password(.:format)                 active_admin/devise/passwords#create
#        new_admin_user_password GET        /admin/password/new(.:format)             active_admin/devise/passwords#new
#       edit_admin_user_password GET        /admin/password/edit(.:format)            active_admin/devise/passwords#edit
#                                PUT        /admin/password(.:format)                 active_admin/devise/passwords#update
#                        animals GET        /animals(.:format)                        animals#index
#                         animal GET        /animals/:id(.:format)                    animals#show
#                          users GET        /users(.:format)                          users#index
#                                POST       /users(.:format)                          users#create
#                       new_user GET        /users/new(.:format)                      users#new
#                      edit_user GET        /users/:id/edit(.:format)                 users#edit
#                           user GET        /users/:id(.:format)                      users#show
#                                PUT        /users/:id(.:format)                      users#update
#                                DELETE     /users/:id(.:format)                      users#destroy
#                       sessions POST       /sessions(.:format)                       sessions#create
#                    new_session GET        /sessions/new(.:format)                   sessions#new
#                        session DELETE     /sessions/:id(.:format)                   sessions#destroy
#                           root            /                                         application#index
#                 privacy_policy            /privacy_policy(.:format)                 pages#privacy_policy
#                         signup            /signup(.:format)                         users#new
#                         signin GET        /signin(.:format)                         sessions#new
#                        signout            /signout(.:format)                        sessions#destroy

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :accept_terms
  has_secure_password

  has_many  :animals

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :email, :first_name, :last_name, :password, :password_confirmation, presence: true
  validates :first_name, :last_name, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }
	validates_acceptance_of :accept_terms, :accept => true, :message => "You must accept the Terms of Serveice & Privacy Policy to continue."

	def full_name
		self.first_name.titleize + " " + self.last_name.titleize
	end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end




# == Schema Information
#
# Table name: users
#
#  id              :integer(4)      not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  accept_terms    :boolean(1)
#  remember_token  :string(255)
#  admin           :boolean(1)      default(FALSE)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_admin_user, 			only: [:index, :destroy]
	before_filter :signed_in_user, 					only: [:edit, :update]
	before_filter :correct_user,   					only: [:edit, :update]
	before_filter :redirect_signed_in_user, only: [:new, :create]

	def index
		@users = User.paginate(page: params[:page], :per_page => 50)
	end

	def show
		@title = User.find(params[:id]).full_name
		@user = User.find(params[:id])
	end

	def new
		@title = "Sign Up"
		@user = User.new
	end

	def create
		@title = "Sign Up"
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Rescue Funder!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@title = "Edit Profile"
	end

	def update
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile Updated"
			sign_in @user
			redirect_to @user
		else
			render "edit"
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User was successfully deleted."
		redirect_to users_url
	end

	private

	def signed_in_user
		unless signed_in?
		  store_location
		  redirect_to signin_url, notice: "Please sign in."
		end
	end

	def redirect_signed_in_user
		redirect_to user_path(current_user) if signed_in?
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user?(@user)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
	<td>
		<div>
			<%= user.full_name %>
		</div>
	</td>
	<td>
		<div><%= user.email %></div>
	</td>
	<td>
		<div>
			<%= link_to user.full_name, user %>
		</div>
	</td>
	<td>
		<div>
			<%= button_to "Delete", user, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this user?" } %>
		</div>
	</td>
</tr>

app/views/users/edit.html.erb
<div class="row">
	<div class="span8">
		<h1>Edit Profile</h1>
		<div class="form-wrapper">
			<%= simple_form_for @user do |f| %>
			  <%= f.input :first_name %>
			  <%= f.input :last_name %>
			  <%= f.input :email %>
			  <%= f.input :password, hint: 'Must be at least 6 characters in length.' %>
			  <%= f.input :password_confirmation, hint: 'Once more for verification please.' %>
			  <%= render 'shared/error_messages' %>
			  <%= f.button :submit, id: "update-account", value: "Save Changes", class: 'btn-info pull-right' %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= will_paginate @users %>
<table class="table table-condensed table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Profile</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<%= render user %>
		<% end %>
	</tbody>
</table>
<%= will_paginate @users %>

app/views/users/new.html.erb
<div class="row">
	<div class="span8">
		<h1>Sign Up for an Account</h1>
		<div class="form-wrapper">
			<p>Already have an account? <%= link_to "Sign In", "#" %></p>
			<%= simple_form_for @user do |f| %>
			  <%= f.input :first_name %>
			  <%= f.input :last_name %>
			  <%= f.input :email %>
			  <%= f.input :password, hint: 'Must be at least 6 characters in length.' %>
			  <%= f.input :password_confirmation, hint: 'Once more for verification please.' %>
			  <%= f.input :accept_terms, :as => :boolean, :label => false, id: "accept_terms"  %> 
			  <label class="accept-label" for="user_accept_terms"> I have read and I accept the <%= link_to "Terms of Service & Privacy Policy", privacy_policy_path %></label>
			  <%= render 'shared/error_messages' %>
			  <%= f.button :submit, id: "create-account", class: 'btn-info pull-right' %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<% if current_user?(@user) %>
	<%= link_to "Edit Profile", edit_user_path %>
<% end %>