config/routes.rb
AnimalRescueHub::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

	resources :animals, :only => [:index, :show]
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'application#index'

  match "/privacy_policy"  => 'pages#privacy_policy'
  match "/signup"          => 'users#new'
  get "signin",           to: "sessions#new"
  #the use of via: :delete for the signout route, which indicates that it should be invoked using an HTTP DELETE request
  match '/signout'         => 'sessions#destroy'

end

#== Route Map
# Generated on 14 May 2013 14:35
#
# batch_action_admin_admin_users POST       /admin/admin_users/batch_action(.:format) admin/admin_users#batch_action
#              admin_admin_users GET        /admin/admin_users(.:format)              admin/admin_users#index
#                                POST       /admin/admin_users(.:format)              admin/admin_users#create
#           new_admin_admin_user GET        /admin/admin_users/new(.:format)          admin/admin_users#new
#          edit_admin_admin_user GET        /admin/admin_users/:id/edit(.:format)     admin/admin_users#edit
#               admin_admin_user GET        /admin/admin_users/:id(.:format)          admin/admin_users#show
#                                PUT        /admin/admin_users/:id(.:format)          admin/admin_users#update
#                                DELETE     /admin/admin_users/:id(.:format)          admin/admin_users#destroy
#     batch_action_admin_animals POST       /admin/animals/batch_action(.:format)     admin/animals#batch_action
#                  admin_animals GET        /admin/animals(.:format)                  admin/animals#index
#                                POST       /admin/animals(.:format)                  admin/animals#create
#               new_admin_animal GET        /admin/animals/new(.:format)              admin/animals#new
#              edit_admin_animal GET        /admin/animals/:id/edit(.:format)         admin/animals#edit
#                   admin_animal GET        /admin/animals/:id(.:format)              admin/animals#show
#                                PUT        /admin/animals/:id(.:format)              admin/animals#update
#                                DELETE     /admin/animals/:id(.:format)              admin/animals#destroy
#                admin_dashboard            /admin/dashboard(.:format)                admin/dashboard#index
#    batch_action_admin_comments POST       /admin/comments/batch_action(.:format)    admin/comments#batch_action
#                 admin_comments GET        /admin/comments(.:format)                 admin/comments#index
#                                POST       /admin/comments(.:format)                 admin/comments#create
#                  admin_comment GET        /admin/comments/:id(.:format)             admin/comments#show
#         new_admin_user_session GET        /admin/login(.:format)                    active_admin/devise/sessions#new
#             admin_user_session POST       /admin/login(.:format)                    active_admin/devise/sessions#create
#     destroy_admin_user_session DELETE|GET /admin/logout(.:format)                   active_admin/devise/sessions#destroy
#            admin_user_password POST       /admin/password(.:format)                 active_admin/devise/passwords#create
#        new_admin_user_password GET        /admin/password/new(.:format)             active_admin/devise/passwords#new
#       edit_admin_user_password GET        /admin/password/edit(.:format)            active_admin/devise/passwords#edit
#                                PUT        /admin/password(.:format)                 active_admin/devise/passwords#update
#                        animals GET        /animals(.:format)                        animals#index
#                         animal GET        /animals/:id(.:format)                    animals#show
#                          users GET        /users(.:format)                          users#index
#                                POST       /users(.:format)                          users#create
#                       new_user GET        /users/new(.:format)                      users#new
#                      edit_user GET        /users/:id/edit(.:format)                 users#edit
#                           user GET        /users/:id(.:format)                      users#show
#                                PUT        /users/:id(.:format)                      users#update
#                                DELETE     /users/:id(.:format)                      users#destroy
#                       sessions POST       /sessions(.:format)                       sessions#create
#                    new_session GET        /sessions/new(.:format)                   sessions#new
#                        session DELETE     /sessions/:id(.:format)                   sessions#destroy
#                           root            /                                         application#index
#                 privacy_policy            /privacy_policy(.:format)                 pages#privacy_policy
#                         signup            /signup(.:format)                         users#new
#                         signin GET        /signin(.:format)                         sessions#new
#                        signout            /signout(.:format)                        sessions#destroy

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>Copyright 2013 Fur & Feathers Fund</p>
	<ul>
		<li>
			<%= link_to "Home", root_path %>
		</li>
		<li>
			<%= link_to "Privacy Policy", privacy_policy_path %>
		</li>
	</ul>
</div>

app/views/layouts/_header.html.erb
<div id="primary-nav" class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<%= link_to root_path, class: "brand" do %>
			<%= image_tag "bg-images/logo.png", alt: "" %>
			<span>Rescue Funder</span>
		<% end %>
		<ul class="nav">
			<li class="divider-vertical"></li>
			<li>
				<%= link_to animals_path do %>
					Browse
					<span>Rescued Animals</span>
				<% end %>
			</li>
			<li class="divider-vertical"></li>
			<li>
				<%= link_to "#" do %>
					Post
					<span>An Animal</span>
				<% end %>
			</li>
			<li class="divider-vertical"></li>
		</ul>
		<ul class="nav pull-right">
			<% if signed_in? %>
				<% if current_user.admin? %>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							Admin
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "All Users", users_path %>
							</li>
						</ul>
					</li>
				<% end %>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						Account
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Profile", current_user %>
						</li>
						<li>
							<%= link_to "#" do %>
								<i class="icons-star-full-no-shadow"></i> Favorites
							<% end %>
						</li>
						<li>
							<%= button_to "Sign Out", signout_path, id: "sign_out", method: "delete" %>
						</li>
					</ul>
				</li>
			<% else %>
				<li>
					<%= link_to "Sign Up", signup_path %>
				</li>
				<li>
					<%= link_to "Sign In", signin_path %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= content_tag :title, title_head %>
		<meta name="description" content="<%= meta_description %>" />
		<%= include_gon %>
	  	<%= stylesheet_link_tag "application", :media => "all" %>
	  	<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Raleway:600|Kotta+One" %>
	  	<%= javascript_include_tag "application" %>
	  	<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</div>
		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
		<%= debug(flash) if Rails.env.development? %>
	</body>
</html>

app/views/layouts/coming_soon.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Rescue Funder</title>
		<meta name="description" content="A platform for animal rescue centers to raise money for a rescued animal. Coming Soon!" />
		<%= stylesheet_link_tag "coming-soon" %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>